# Практика по математике

## Линейная алгебра

In [19]:
import numpy as np

In [20]:
a = np.arange(9).reshape(3, 3)
print(a)
print("Shape is " + str(a.shape))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape is (3, 3)


In [21]:
v1 = np.array([1, 1, 0])
v2 = np.array([2, -2, 0])
v1.dot(v2)

0

In [22]:
vectors = np.array([v1, v2])
vectors

array([[ 1,  1,  0],
       [ 2, -2,  0]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [26]:
r = np.random.random((2,3))
r

array([[0.98145358, 0.20130221, 0.9368608 ],
       [0.58974556, 0.64550449, 0.61281114]])

In [27]:
def f(x,y):
  return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [28]:
print(b[2,3])
print(b[0:5, 1])
print(b[ : ,1])
print(b[1:3, : ])

23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


### Операции

In [29]:
A = np.arange(4).reshape((2,2))
v1 = [1, 2, 3, 4]
v2 = [-2, -4, -6, -8]
A

array([[0, 1],
       [2, 3]])

In [30]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [34]:
a = A

In [35]:
#- Вот так берется определитель
np.linalg.det(a)

-2.0

In [36]:
#- Вот так берется обратная матрица
np.linalg.inv(a)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [38]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [39]:
x = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
y = np.array([[7, 8, 9], [4,5,6], [1,2,3]])
np.cross(x, y)

array([[ -6,  12,  -6],
       [  0,   0,   0],
       [  6, -12,   6]])

In [40]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

In [41]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [42]:
u = np.eye(4)
u

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
M = np.matrix([[1,2,3],
               [4,5,6]])
M

matrix([[1, 2, 3],
        [4, 5, 6]])

In [48]:
#- Написать функцию, вычисляющую аналитическое решение линейной регрессии
from sklearn.datasets  import load_boston
X, y = load_boston().data, load_boston().target
X, y

(array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 1

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train = [[1] + x for x in X_train]
X_test = [[1] + x for x in X_test]

theta = np.linalg.inv(np.transpose(X_train).dot(X_train)).dot(np.transpose(X_train)).dot(y_train)
y_pred = []
for x in X_test:
    cur = 0
    for a, b in zip(x, theta):
        cur += a * b
    y_pred.append(cur)
mean_squared_error(y_test, y_pred)

22.833377570520263